import argparse

class ConvertToBytes(argparse.Action):
    def __init__(self, option_strings, dest, nargs=None, **kwargs):
        super(ConvertToBytes, self).__init__(option_strings, dest, **kwargs)
    def __call__(self, parser, namespace, values, option_string=None):
        setattr(namespace, self.dest, bytes.fromhex(values))

def get_args():
    """Returns the args required for the script ptokens_verify"""
    parser = argparse.ArgumentParser(
        description='-- Verifify pTokens attestations utility --',
        usage='./%(prog)s [OPTIONS] <filename> <64-hex-digits>  <64-hex-digits>'
    )

    parser.add_argument(
        'filename',
        help='JSON file generated by the application'
    )

    parser.add_argument(
        'apkhash',
        action=ConvertToBytes,
        help="""sha256 digest of the application package (Hex string)
                  You get this by doing:
                      > sha256sum <apkname>.apk
        """
    )

    parser.add_argument(
        'apkcerthash',
        action=ConvertToBytes,
        help="""sha256 digest of the application package signing certificate (Hex string)
                  You get this by using apksigner provided by the Android SDK:
                      > apksigner verify --print-certs <apkname>.apk
        """
    )

    parser.add_argument(
        '--stdout',
        action='store_true',
        help="prints logging to stdout"
    )

    parser.add_argument(
        '--logging',
        default='i',
        help="set logging level"
    )

    parser.add_argument(
        '--version',
        action='version',
        version='%(prog)s 1.2'
    )

    return parser.parse_args()
